CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "email" varchar(150) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "role" varchar(30) NOT NULL,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp
);

CREATE TABLE "password_resets" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "reset_code" varchar(120) NOT NULL,
  "expires_at" timestamp NOT NULL,
  "used_at" timestamp,
  "created_at" timestamp NOT NULL
);

CREATE TABLE "events" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_by" integer NOT NULL,
  "name" varchar(150) NOT NULL,
  "description" text,
  "event_type" varchar(50) NOT NULL,
  "modality" varchar(30) NOT NULL,
  "location" varchar(180),
  "start_datetime" timestamp NOT NULL,
  "end_datetime" timestamp,
  "total_capacity" integer NOT NULL,
  "available_capacity" integer NOT NULL,
  "status" varchar(30) NOT NULL,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp,
  "updated_by" integer
);

CREATE TABLE "reservations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "event_id" integer NOT NULL,
  "quantity" integer NOT NULL,
  "status" varchar(30) NOT NULL,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp
);

CREATE TABLE "simulated_payments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reservation_id" integer UNIQUE NOT NULL,
  "holder_name" varchar(100) NOT NULL,
  "masked_card_number" varchar(25) NOT NULL,
  "amount" decimal(10,2) NOT NULL,
  "result" varchar(30) NOT NULL,
  "processed_at" timestamp NOT NULL,
  "created_at" timestamp NOT NULL
);

CREATE TABLE "tickets" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reservation_id" integer NOT NULL,
  "ticket_code" varchar(120) UNIQUE NOT NULL,
  "qr_code_url" varchar(255),
  "status" varchar(30) NOT NULL,
  "generated_at" timestamp NOT NULL,
  "used_at" timestamp,
  "user_id" integer NOT NULL
);

CREATE TABLE "ticket_validations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ticket_id" integer NOT NULL,
  "validated_by" integer NOT NULL,
  "validation_result" varchar(30) NOT NULL,
  "validation_datetime" timestamp NOT NULL,
  "notes" text
);

COMMENT ON COLUMN "users"."role" IS 'user, admin';

COMMENT ON COLUMN "events"."event_type" IS 'event, service';

COMMENT ON COLUMN "events"."modality" IS 'presencial, virtual, hibrido';

COMMENT ON COLUMN "events"."status" IS 'available, sold_out, finished, cancelled';

COMMENT ON COLUMN "reservations"."status" IS 'pending_payment, confirmed, rejected, cancelled';

COMMENT ON COLUMN "simulated_payments"."masked_card_number" IS 'Only last digits or masked value';

COMMENT ON COLUMN "simulated_payments"."result" IS 'approved, rejected';

COMMENT ON COLUMN "tickets"."status" IS 'active, used, cancelled';

COMMENT ON COLUMN "ticket_validations"."validation_result" IS 'valid, invalid, already_used';

ALTER TABLE "password_resets" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "events" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reservations" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reservations" ADD FOREIGN KEY ("event_id") REFERENCES "events" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "simulated_payments" ADD FOREIGN KEY ("reservation_id") REFERENCES "reservations" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tickets" ADD FOREIGN KEY ("reservation_id") REFERENCES "reservations" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ticket_validations" ADD FOREIGN KEY ("ticket_id") REFERENCES "tickets" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ticket_validations" ADD FOREIGN KEY ("validated_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tickets" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "events" ADD FOREIGN KEY ("updated_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

CREATE TABLE "notifications" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "type" varchar(50) NOT NULL,
  "title" varchar(150) NOT NULL,
  "message" text NOT NULL,
  "data" text,
  "status" varchar(30) NOT NULL,
  "created_at" timestamp NOT NULL
);

COMMENT ON COLUMN "notifications"."status" IS 'unread, read';

ALTER TABLE "notifications" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
